//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Encore.Localisations;

namespace Unity.VisualScripting.Generated.PropertyProviders
{


    [global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(LocalisedString))]
	public class PropertyProvider_LocalisedString : Unity.VisualScripting.SerializedPropertyProvider<LocalisedString>
	{
	}
}
